rq/rq-scheduler

README.rst

Right now, there's no explicit warning for the fact that, if you set a low result TTL value, the key will expire and the job will not get re-scheduled.

Added warning for setting result ttl value for repeated jobs to the Readme file

---

rq_scheduler/scripts/rqscheduler.py
rq_scheduler/utils.py

Same as `rq.logutils.setup_loghandlers()` but wirth the correct logger. I suppose the initial intention was to "do it how `rq` does", so it should be fine.

Configure logger (fix #69)

---

README.rst

The readme says the new crontab functionality was introduced in v0.5.2 but it should read v0.6.0.

Fix readme to display correct version.

---

rq_scheduler/scheduler.py
tests/test_scheduler.py

While this adds support for `timeout` only, why is `cron` missing the other relevant parameters (`ttl`, `id` and `description`)?

Added support for setting the job timeout when scheduling jobs via cron.

---

rq_scheduler/scheduler.py

Jobs scheduled via `Scheduler.cron` expire automatically after 500 sec if the time between two job executions exceeds 500 sec.

Jobs scheduled via cron no longer expire automatically after 500 sec.

---

rq_scheduler/scheduler.py
rq_scheduler/utils.py
tests/test_scheduler.py

Added `get_job_count()` and `get_job_count_by_queue()` to `Scheduler` and associated tests.
Closes #118. Probably required for
https://github.com/ui/django-rq/pull/121.

Implement count() methods

---

rq_scheduler/scheduler.py
tests/test_scheduler.py

Scheduler._create_job()
*  now accepts also timeout argument
* added test for above
* cleanup of scheduler methods that were setting timeout not by `_create_job`
Scheduler.enqueue_at() + Scheduler.enqueue_in():
* added timeout argument that is popped from kwargs

Timeout argument for ._create_job(), .enqueue_at(), enqueue_in()

---

rq_scheduler/scheduler.py
tests/test_scheduler.py

Here is an updated PR for multiple schedulers support (GH-104).
refs #70

Multi schedulers

---

rq_scheduler/scheduler.py
tests/test_scheduler.py

Schedulers have to acquire a lock before one can schedule jobs. The
lock automatically expires in case a scheduler is terminated unexpectedly.
Schedulers that cannot acquire a lock will sleep for the duration of
polling interval before retrying.
refs #70

Allow multiple schedulers to run

---

rq_scheduler/scheduler.py
tests/test_scheduler.py

I had a need to specify a job id when scheduling a job, so I made the trivial modification to the enqueue_in and enqueue_at methods. Since RQ.Queue.enqueue supports the job_id parameter, it seems like a reasonable name to use for the public Scheduler methods.

Update scheduler.enqueue_at/in to accept job_id argument

---

rq_scheduler/scheduler.py

This PR makes `run()` wait only long enough so that the seconds _since last time `enqueue_jobs()` was called_ is waited.   Currently, `run()` would sleep `interval` seconds even though it already took some time to `enqueue_jobs()`.  With this fix, we're pretty-well guaranteed each repeated run is exactly `interval` seconds apart instead of `interval` number of seconds since the last time jobs _finished_ enquing.

Make `run()` repeat exactly every `interval` number of seconds

---

rq_scheduler/scheduler.py
tests/test_scheduler.py

In some cases, I had to specify job ttl and result ttl when scheduling a job, so I made the minor patch to the enqueue_in and enqueue_at methods similar to a job_id argument.

Updated enqueue_in/at to accept job_ttl and job_result_ttl arguments

---

rq_scheduler/scripts/rqscheduler.py

RQScheduler will consistently pour "Checking for scheduled jobs..." into the console at a very fast clip, depending on the interval. In this PR, I add a `-q` or `--quiet` that does the opposite of `--verbose` and tones down logging to WARNING or above.

Add "-q" flag that will silence INFO messages

---

rq_scheduler/scheduler.py

All the other functions also take the `description` kwarg except for `enqueue_at` and `enqueue_in`, so in this PR I added the field as `job_description` (in keeping with the other kwargs).
I also added a clarifying comment that the functions will swallow the kwargs that are used to create the job itself. Someone on our team noted this and I thought it would be helpful to note-- however there is no change in the behavior itself, just documenting it :)

Add optional job descriptions to enqueue_at and enqueue_in

---

rq_scheduler/scheduler.py
tests/test_scheduler.py

Currently the scheduler looks for the queue with `Queue.queue_from_key()`, which can be inadequate in cases where we want a Queue object with properties that are not saved in Redis (for example, `async=False`). This change makes it possible to bind the scheduler to a specific queue, instead of looking for it by name and creating the object.

Add ability to pass Queue objects to scheduler

---

README.rst
rq_scheduler/scheduler.py
rq_scheduler/scripts/rqscheduler.py
setup.py

This enables custom job/queue classes to be used in scheduler the same way as it is possible in rq (since 0.8). No additional code paths, just changing Job/Queue to swappable attributes, therefore tests should cover this as is.

support custom job/queue classes, update rq dependency accordingly

---

rq_scheduler/scheduler.py
tests/test_scheduler.py

In some cases, there may be a lot of jobs in a schedule interval, that will cause get_jobs to return a very large list, and the memory using rises greatly. The jobs returned will be enqueued one by one, so an iterator may be better here.

get_jobs returns iterator

---

README.rst
rq_scheduler/scheduler.py
tests/test_scheduler.py

Allow arbitrary pickleable data to be attached to a job created by the scheduler.
> To add/update custom status information on this job, you have access to the meta property, which allows you to store arbitrary pickleable data on the job itself ~ http://python-rq.org/docs/jobs/
Addresses Issue #187

Add meta parameter for Job instances

---

rq_scheduler/scheduler.py
tests/test_scheduler.py

The queue of the job was getting overridden by the Scheduler queue. The queue of the job should remain the same.

FIX: Job gets queued to the same queue.

---

.gitignore
.travis.yml
README.rst
rq_scheduler/scheduler.py
rq_scheduler/utils.py
tests/test_scheduler.py

This is an improved version of #168
- Properly reschedule with local TZ on second execution
- Added docs
- Added rescheduling test
- Rebased

Add optional argument to use local timezone for cron-scheduled jobs (redux)

---

rq_scheduler/scheduler.py

When debugging it is not very user friendly it just shows the job.id. This change adds the function name to help debug problems.
The current log output looks something like this:
```
Pushing fdfc4e56-22fa-474f-9378-e6dad47f5fc9 to default-medium
```
I think we can all agree that after 5 or 10 scheduled jobs this becomes pretty meaningless. I propose this:
```
Pushing path.to.func_name(fdfc4e56-22fa-474f-9378-e6dad47f5fc9) to default-medium
```

Add function name to the debug logs

---

rq_scheduler/scheduler.py
tests/test_scheduler.py

RQ allows jobs to be dependent on others. Its enqueuing methods accept a job dependency via a  "depends_on" argument. RQ-scheduler's enqueue_in and enqueue_at methods should also allow for this.
There was pull request with similar goals 6 years ago, but for some reason it was never accepted, and it's now outdated: https://github.com/rq/rq-scheduler/pull/56.

Depends on

---

rq_scheduler/scheduler.py
tests/test_scheduler.py

This PR is in reference to issue #195 
It adds the feature of running multiple scheduler instances (on multiple servers).
Each scheduler registers itself, then tries to acquire a lock to process the scheduling work. If the lock gets acquired it will schedule the jobs to the appropriate queues, remove the lock, and sleep for it's interval.
In the meanwhile another scheduler can try to acquire the lock. If it fails, it will simply sleep for its interval and try again later.
This way we don't have a single scheduler doing all the work. Different schedulers may acquire the lock at different time instances.
I've made sure that even those schedulers who can't acquire a lock have still registered their birth and a heartbeat makes sure the scheduler instance key doesn't expire even if the …

Feature: Multiple Schedulers

---

README.rst

I've added some basic info about running Multiple Schedulers (#212 & #195 ) in the README file, along with a practical example.
Let me know if I've missed something! ^_^
Thanks.

docs: add multiple scheduler info

---

README.rst
rq_scheduler/scheduler.py
tests/test_scheduler.py

By default, rq-scheduler allowed to choose the queue type when the `run` process of rq-scheduler was started. These queue type was used for all scheduled jobs. You weren't able to choose an specific queue type for each job, they used the same queue type.
This PR allows choose the queue type of each job when it is scheduler. The param `queue_class` it's stored as job metadata when the job is scheduled.
Then when de job is queued the rqscheduler checks if the job has an especific `queue_class` defined and uses it. If there is no `queue_class` in the meta data of the job then the queue_class of the main rq-scheduler is used.

Allow chose queue type when the job is scheduled

---

setup.py

The dependency of `tests_require` is for python 2.4/2.5/2.6 and no more supported.

remove useless tests_require

---

rq_scheduler/utils.py
setup.py
tests/test_scheduler.py

`to_unix` ignores TZ information - force all dates returned by `get_next_scheduled_time` to be TZ-aware and in the expected TZ right away.
⚠️ this adds dependency to `python-dateutil` for local timezone detection

fixed local TZ handling - fixes #247

---

README.rst

When instantiating a Scheduler with a custom RQ Queue as per the README, it fails with:
rq.connections.NoRedisConnectionException: Could not resolve a Redis connection
This change adds the explicit `connection` attribute required to use a custom queue.
fixes #228

Fix custom queue instructions in README
